<?php
/**
 * TL_ROOT/system/modules/development/languages/de/modules.php 
 * 
 * TYPOlight extension: development 1.0.0 stable 
 * German translation file 
 * 
 * Copyright : ©2005-2009 Leo Feyer 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Leo Feyer (leo), http://www.inetrobots.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MOD']['be_infopage'] = array('Info Webseite', 'Infos Webseite anzeigen');
 
?>